### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by jovanpreet** [MailOnline/ImageViewer#103]
Is there a way to play audio with custom galleryItem. Or are you planning for some update with audio support?

**Comment by zfoltin** [comment]
Hi @jovanpreet 

I can see two ways you could achieve audio playback in the gallery:

1. Implement the `landedPageAtIndexCompletion` callback where you can start / stop playing audio when the gallery arrives to a given page
2. If you want more control (eg: playback controls, extra/interactive visuals) then you can implement a custom `GalleryItem` which can provide its own ViewController (see the example app for how to do it)

If you can come up with a generic solution that fits well into ImageViewer (eg: a built-in `GalleryItem.audio` implementation with some default play/pause/stop buttons) we would love to see a PR for it ❤️

Hope this helps

**Comment by Krisiacik** [comment]
That would be  nice addition. I am strongly in favour of having that as distinct gallery item.

**Comment by jovanpreet** [comment]
Currently i am busy. I would love to do that and might do when my app gets published.

**Comment by RuiAAPeres** [comment]
Any update on this @jovanpreet ?

**Comment by jovanpreet** [comment]
@RuiAAPeres No I didn't use this library and created my own.

**Comment by RuiAAPeres** [comment]
👍
