### ISSUE TITLE
Thumbnail mode

### ISSUE THREAD

**Issue by demon9733** [MailOnline/ImageViewer#105]
Is there a way to open in thumbnail (gallery) mode initially?
ThumbnailViewController is not an open class for now..

**Comment by zfoltin** [comment]
As you pointed out ThumbnailsViewController is not open atm. Can't see why we couldn't make it open. Feel free to submit a PR with the change 👍

**Comment by demon9733** [comment]
It didn't quite help actually. ThumbnailViewController initially doesn't have a selector for opening (tapping) a cell.
So the only way is to init GalleryViewController first. But I still haven't achieved a stable work and desired behaviour :(

**Comment by zfoltin** [comment]
I don't quite understand the problem. If ThumbnailsViewController was `open` you could create and present one like we do from `GalleryViewController` (see https://github.com/MailOnline/ImageViewer/blob/master/ImageViewer/Source/GalleryViewController.swift#L397) where you can also set up the `onItemSelected` callback

Does this help?

**Comment by Krisiacik** [comment]
I suspect the issue is 
open(visually) != open(acces level)
