### ISSUE TITLE
Autoplay videos when opened

### ISSUE THREAD

**Issue by ealymbaev** [MailOnline/ImageViewer#106]
I need an ability to start playing videos immediately when they are opened.

**Comment by zfoltin** [comment]
PRs are more than welcome! 👍 I'd suggest adding a new `GalleryConfigurationItem`

**Comment by Krisiacik** [comment]
I was wondering what can be more than welcome.
Very welcome? 🤔

 😉

**Comment by oxozle** [comment]
Autoplay video PR https://github.com/MailOnline/ImageViewer/pull/120
