### ISSUE TITLE
Rotation issue when closing in landscape mode

### ISSUE THREAD

**Issue by winkelsdorf** [MailOnline/ImageViewer#108]
`ImageViewer` does not handle common device rotation correctly when being closed.

**Steps to reproduce**
- Adjust Demo to allow Landscape Orientation
<img width="412" alt="screenshot 2017-01-31 19 05 33" src="https://cloud.githubusercontent.com/assets/1413291/22477946/46ae3ba8-e7e8-11e6-893f-a7a37f88610a.png">

- Launch Device in Portrait (e.g. iPhone 6+, iOS 9)
- Tap on Image
- Rotate Device
- Close Image by using "X" Button

**Alternate Steps**
- Rotate Device before tapping Image
- Tap Image
- Close Image by using "X" Button

**Expected**
- Image closing to `DisplaceableView`

**Result**
- Image closing to `DisplaceableView` but rotating wrongly during close

**Further Details**
Using latest commit https://github.com/MailOnline/ImageViewer/commit/65a0a235bafd2a0b2212c86fd92f23fc4be5b5b2.

**Issue Preview**
![imageviewer rotation bug](https://cloud.githubusercontent.com/assets/1413291/22478227/5a30b3d0-e7e9-11e6-9fa2-bc65e109a6f8.gif)

**Comment by zfoltin** [comment]
Excellent bug report @winkelsdorf 
Will try to look into it ASAP

**Comment by winkelsdorf** [comment]
@zfoltin You're welcome, thanks having a look into!

**Comment by winkelsdorf** [comment]
I don't understand the complicated rotation handling implemented in `ImageViewer` yet, but I can imagine it's needed for cases where your applications usually run in portrait-only mode and you would like to override this for the `ImageViewer` while allowing to revert back to the previous displacement items.

Probably this would have been easier alongside using `open override var supportedInterfaceOrientations: UIInterfaceOrientationMask`?

When using `.rotationMode(.applicationBased)` it shouldn't be needed at all.

Anyway, regarding the reported bug, if I comment out your custom rotation handling in `ItemBaseController`´s method `public func dismissItem(alongsideAnimation: () -> Void, completion: @escaping () -> Void)` at line L525 it works:
```swift
    public func dismissItem(alongsideAnimation: () -> Void, completion: @escaping () -> Void) {

        guard isAnimating == false else { return }
        isAnimating = true

        alongsideAnimation()

        switch presentationStyle {

        case .displacement:

            if var displacedView = self.findVisibleDisplacedView() {

                if displacementKeepOriginalInPlace == false {
                    displacedView.hidden = true
                }

                UIView.animate(withDuration: reverseDisplacementDuration, animations: { [weak self] in

                    self?.scrollView.zoomScale = 1

                    //rotate the image view
//                    self?.itemView.transform = deviceRotationTransform()
```

Of course this probably breaks other places but at least it's the line causing the problem.
