### ISSUE TITLE
Can't close viewer with gesture while image is loading

### ISSUE THREAD

**Issue by antonkiselev** [MailOnline/ImageViewer#110]
If user has poor network connection and fetchImageBlock takes quite some time to complete, it is impossible co close viewer with gesture due to

```
func scrollViewDidSwipeToDismiss(_ recognizer: UIPanGestureRecognizer) {

        /// a swipe gesture on image view that has no image (it was not yet loaded, so we see a spinner) doesn't make sense
        guard itemView.image != nil else {  return }
```

Could you please make this behaviour optional?

Would really appreciate if you pushed it to master branch asap.

**Comment by Nonepse** [comment]
I am facing the same issue :(

**Comment by Ricardo1980** [comment]
Same problem here

**Comment by RuiAAPeres** [comment]
Is there a PR for this behaviour?

**Comment by ed-mejia** [comment]
+1

**Comment by antonkiselev** [comment]
> Is there a PR for this behaviour?
Nope, i just forked it and fixed for myself, and also added custom loader instead of default one, and because it partly removed default loader styling I didn't make a pull request. Feel free to copy my repo, or check commits there.

Actually viewer has some major flaws like using gesture recognizers on each image view instead of one on the wrapper, not using presentation mechanics like UIPercentDrivenInteractiveTransition, presenting controller instantly and then pretending to present. I spent few hours trying to rewrite it, but everything is so glued together with value observers, private properties and such, so i gave up and just added what was needed for my app.
