### ISSUE TITLE
Need a fetchVideoBlock

### ISSUE THREAD

**Issue by leacode** [MailOnline/ImageViewer#121]
Can you provide a fetchVideoBlock. Sometimes loading video progress is needed. Another problem is when I swipe to close the view  it crashes. Log is here: 

An instance 0x1700139a0 of class AVPlayer was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x1704359e0> (
<NSKeyValueObservance 0x17045dbe0: Observer: 0x137daf5e0, Key path: status, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x17044e100>
<NSKeyValueObservance 0x17045dc40: Observer: 0x137daf5e0, Key path: rate, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x17044e3a0>
)'

**Comment by oxozle** [comment]
You can use my solution to this crash from this PR https://github.com/MailOnline/ImageViewer/pull/120
