### ISSUE TITLE
How can I use this library to just show a single image

### ISSUE THREAD

**Issue by ed-mejia** [MailOnline/ImageViewer#125]
related to issue #92 ...

If you provide itemCount 1, the library allows you to swipe right left anyway and keep asking the datasourse for the next/ previous item making impossible to actually display a single element.

Any ideas?

**Comment by mikengyn** [comment]
you can set the `swipeToDismissMode` to `always`.

**Comment by ed-mejia** [comment]
Thanks @mikengyn 👍
