### ISSUE TITLE
Missing GalleryConfigurationItem enum

### ISSUE THREAD

**Issue by happiehappie** [MailOnline/ImageViewer#128]
I tried to directly copy the configuration from the example project however the following enum cases are missing.
GalleryConfigurationItem.swipeToDismissMode(.vertical)
GalleryConfigurationItem.toggleDecorationViewsBySingleTap(false)
GalleryConfigurationItem.maximumZoomScale(8)

There are also some that are not in the example but is in the source file, example SeeAllCloseButtonMode

Tried pod update but the source file are still missing these.
Attached an empty project with only the podfile showcasing the same issue.
[TestImageViewerPod.zip](https://github.com/MailOnline/ImageViewer/files/908929/TestImageViewerPod.zip)

**Comment by zfoltin** [comment]
The Pod is out of date. With release 4.1.0 this issue should go away
