### ISSUE TITLE
Videos with no sound

### ISSUE THREAD

**Issue by mamdouhweb** [MailOnline/ImageViewer#134]
while running on phone (IPhone7) the video has no sound to it and getting this error back
```
[MediaRemote] Error Operation requires a client callback to have been registered. requesting playback queue
```

however, in the simulator it's working perfectly. I ran the provided example to make sure that it's not caused by my backend, and the sound was also not there while running on Device.

Any help is really appreciated!

**Comment by zfoltin** [comment]
Haven't come across this issue. Can you check if your phone is not muted? And post a video which causes this issue?
