### ISSUE TITLE
Remove "See All"

### ISSUE THREAD

**Issue by iad24** [MailOnline/ImageViewer#148]
I just want to show the X button at the top right and the image. No other buttons like "See All".
I could not find a property to hide this.

**Comment by ra-mentukemen** [comment]
`let gvc = GalleryViewController(startIndex: 0, itemsDataSource: self, configuration: [ .thumbnailsButtonMode(.none)])`
        
`presentImageGallery(gvc)`

**Comment by zfoltin** [comment]
@iad24 does `.thumbnailsButtonMode(.none)` solve your issue?

**Comment by iad24** [comment]
thanks @ra-mentukemen

**Comment by iad24** [comment]
@zfoltin yes
