### ISSUE TITLE
Localize framework?

### ISSUE THREAD

**Issue by CeceXX** [MailOnline/ImageViewer#156]
I want to translate "See All" to my app lanugage. Is it possible?

**Comment by RuiAAPeres** [comment]
AFAIK no, we would have to allow the injection. 😞

**Comment by RuiAAPeres** [comment]
@CeceXX just to be clear, I don't feel this would particularly difficult to achieve. If you could open an issue with a bit more detail, I could then create a PR.

**Comment by CeceXX** [comment]
Hey Rui, thanks for the heads up. So basically I just wanted to know if it was possible to have all the text elements to be localized in my app language. E.g. have a few localizable strings (using NSLocalizableString). I'll comment again with more information.
