### ISSUE TITLE
Type 'UIImageView' does not conform to protocol 'DisplaceableView'

### ISSUE THREAD

**Issue by terrytz** [MailOnline/ImageViewer#159]
Did i do something wrong or is it compatibility issue with swift 4?

**Comment by zfoltin** [comment]
@terrytz the Swift 4 related updates haven't been pushed to cocoapods (coming very soon). Are you pointing to the master branch of the repo in your podspec?

**Comment by terrytz** [comment]
I wasn’t using cocoa pods , it was straight git clone from master

**Comment by RuiAAPeres** [comment]
@terrytz can you show me what's your error?

**Comment by terrytz** [comment]
I copied the code straight up from the example file, and got this error

<img width="786" alt="screen shot 2017-10-05 at 5 03 26 am" src="https://user-images.githubusercontent.com/3625602/31199631-a0753474-a91d-11e7-9bc2-ca598fe802b1.png">

**Comment by springlo** [comment]
```
extension UIImageView: DisplaceableView {}
```
