### ISSUE TITLE
How to pass image into the ImageView?

### ISSUE THREAD

**Issue by LeeMing988** [MailOnline/ImageViewer#16]
Hello, 

   By refer to your code, I wonder how I can pass my selected Image to display?

```
class PoorManProvider: ImageProvider {
    
    func provideImage(completion: UIImage? -> Void) {
        completion(UIImage(named: "image_big"))
    }
}
```

**Comment by Krisiacik** [comment]
Hi,
this is not how it works strictly speaking. There are two steps. One is mandatory , the second is optional.
Step 1) you provide a **reference** to a (displaced) view - image viewer makes a screenshot of it and this screenshot is what is animated.
Step 2) You provide a reference to an object that complies to the ImageProvider protocol.
Image viewer then calls the provideImage method on this object and passes a block to that method. IT is that block that consumes the image that the provider provides. The last question is where is the image coming from? You need to get it aside the provideImage method.  

`class PoorManProvider: ImageProvider {

    func provideImage(completion: UIImage? -> Void) {
       let image =  <GET THE IMAGE HERE >

        completion(UIImage(named: image))
    }
}`

**Comment by RuiAAPeres** [comment]
@LeeMing988 adding to what @Krisiacik said: the idea is to decouple the presentation layer (our lib) from the model layer (**what** provides the image). This way you are free to use whatever you want to download the image and not coupled to our own implementation. I would advise [Nuke](https://github.com/kean/Nuke) for example.
