### ISSUE TITLE
Import in Objective C

### ISSUE THREAD

**Issue by erngarcar** [MailOnline/ImageViewer#160]
Hi, I'm trying import this library in a objective-c project, but I'm only able to get GalleryViewController, not a GalleryItem for example.
Could you tell me how to import this library in the correct way on a objective-c project?
Best regards.

**Comment by RuiAAPeres** [comment]
`GalleryItem` is an enum with associated types and in objc you can't use those:

![screen shot 2017-10-04 at 20 56 55](https://user-images.githubusercontent.com/949286/31196702-9aa5790e-a946-11e7-9dea-2f6828d173a0.png)
