### ISSUE TITLE
Change position of close button to left

### ISSUE THREAD

**Issue by ELezov** [MailOnline/ImageViewer#162]
I can't find this.

Can I change position of button?

**Comment by zfoltin** [comment]
Take a look at the `closeLayout` configuration option https://github.com/MailOnline/ImageViewer/blob/master/ImageViewer/Source/GalleryConfiguration.swift#L34
https://github.com/MailOnline/ImageViewer/blob/master/ImageViewer/Source/LayoutEnums.swift#L16

Hope this helps

**Comment by ELezov** [comment]
thanks a lot
