### ISSUE TITLE
iPhone X Support

### ISSUE THREAD

**Issue by joeljfischer** [MailOnline/ImageViewer#164]
Hi, when using the default (no changes to configuration) with the iPhone X simulator, and some buttons at the top seem to be getting cut off by the notch. How could I mitigate this, or is there a fix coming? Does it need to be using the safe areas?

**Comment by zfoltin** [comment]
Lovely flower @humblehacker :) The iPhone X's revolutionary new design is a PITA... Maybe the best would be just to offer a configuration option for `UIEdgeInsets` from the screen edge so then everyone can set whatever margin they fancy? The safe area margins do look a bit to much to me too.
@Krisiacik thoughts?

**Comment by humblehacker** [comment]
It's already externally configurable via `GalleryConfiguration`, but I thought it would be nice if it worked out-of-the-box.

And I can't take credit for the flower - it's from the sample app 😄

**Comment by zfoltin** [comment]
Lol. It's been a while I last run the sample 🤣 Also forgot about the config option... Guess using the safe area as a default is a safe default even if it makes things look a bit out of place

**Comment by humblehacker** [comment]
So the extra top space also appeared when I ran on iOS 11 on a non-iPhone X.  I discovered that the top `safeAreaInsets` had an extra 20px of space - presumably to account for the status bar, which is of course hidden.  Seems like a bug, so I compensated for it as you can see in PR #169 .  With that compensation, the layouts are the same on iOS 10 and iOS 11 for the same device.  And it looks better on the iPhone X.

![](https://www.dropbox.com/s/62psk2tbenbhk1f/ImageView_iPhone_X_corrected.png?raw=1)
