### ISSUE TITLE
Add an option to customise the main background colour.

### ISSUE THREAD

**Issue by Krisiacik** [MailOnline/ImageViewer#21]
At the moment the main background colour is hardcoded to black.

**Comment by chuckurbis** [comment]
Another thing that would be nice in this enhancement, would be to either default, or have an option to set the screenshot made via the screenshotFromView method in UtilityFunctions.swift, not default to opaque. 

So it would be: 
`    UIGraphicsBeginImageContextWithOptions(view.bounds.size, false, UIScreen.mainScreen().scale)
`

This allows for rounded images to full screen up without a black area filling the borders.

**Comment by Krisiacik** [comment]
Cool idea. We will do it. 
[#25](https://github.com/MailOnline/ImageViewer/issues/25)

**Comment by goatmad** [comment]
Just found out about this being hardcoded, and everything being declared final so no overrides can be done.  Does anyone have a temporary solution to change the background color?

I tried using landedPageAtIndexCompletion to change the background color, but obviously that happens after the view finishes animating to place.
