### ISSUE TITLE
Add action button support via delegate

### ISSUE THREAD

**Issue by ZahidKsoft** [MailOnline/ImageViewer#23]
Please add Activity view controller support via delegate method so that the sharing and all those default features can be used over the image

**Comment by Krisiacik** [comment]
You already have optional completion blocks. Together with publicly accessible current index and injectable decoration views, you can implement social sharing without changes to our current codebase. 
I'll consider delegate callbacks for the same states, it's nothing too difficult, why not... But I wanted to highlight there is nothing stopping you from having social sharing right now.

Let me know what you think.

**Comment by aadjemonkeyrock** [comment]
I'm implementing sharing, I've it all working with the points mentioned, but I get stuck on presenting the UIActivityViewController. I'm presenting this from the same ViewController as is presenting the GalleryViewController, but get the message 'attempt to present .... is already presenting. I need to present from the GalleryViewController, but I've no idea how to do this. 

Does anyone have a complete example?
