### ISSUE TITLE
presenting displaced view maintains its image size, does not fit to new ImageView bounds

### ISSUE THREAD

**Issue by ahusseini** [MailOnline/ImageViewer#30]
Hello, when passing a `UIImageView` (which has a `contentMode` of `.ScaleAspectFit`) as a displaced view, `GalleryViewController` maintains the image size. If the image is fit by height it maintains the aspect ratio and does not layout to the new bounds.

passing first image as displaced: 

<img src="https://cloud.githubusercontent.com/assets/6011755/15658514/44a09a96-268b-11e6-8466-c79c3a9f8983.png" width="100">

switching to next image: 

<img src="https://cloud.githubusercontent.com/assets/6011755/15658517/550627de-268b-11e6-8fdb-2c74e17adc87.png" width="100">

passing second image as displaced:

<img src="https://cloud.githubusercontent.com/assets/6011755/15658519/5d22e006-268b-11e6-942d-31c5bca90a6f.png" width="100">

switching to first image:

<img src="https://cloud.githubusercontent.com/assets/6011755/15658521/6590af7a-268b-11e6-92e6-5aa803900413.png" width="100">

**Comment by Krisiacik** [comment]
Thanks! We will have to take a look.

**Comment by Krisiacik** [comment]
Hi...could you please provide the original image as well as measure the size of the original UIImageView instance and let us know what it is? I'd like to reproduce this 100%.

**Comment by ahusseini** [comment]
Hello, sorry for the late reply. Some background info: the `UIImageView` is in a `UICollectionViewCell` it's height is 300px and its width is the device's width.

here is the image: 

![homer](https://cloud.githubusercontent.com/assets/6011755/15750332/07b041ce-28b4-11e6-84c6-837bd68e5526.png)

**Comment by Krisiacik** [comment]
Some update:  This is a hard problem, from design /UX perspective.. I have still not decided what the correct action should be...but I am trying :)

**Comment by RuiAAPeres** [comment]
@ahusseini could you try #42 to see if it fits your needs?

**Comment by ahusseini** [comment]
Thank you, I'll test this out tonight and let you know.

**Comment by ahusseini** [comment]
Tried out @zfoltin's solution, it resolves this issue and smoothly animates the transition (which was a bonus). Thank you all for your help!
