### ISSUE TITLE
ImageViewer that is never presented will crash on deinit

### ISSUE THREAD

**Issue by yuriramocan** [MailOnline/ImageViewer#31]
If an `ImageViewer` is created but never presented, its various view properties, namely `scrollView`, will never be initialized, and so will crash the app in `deinit` when `scrollView.removeObserver(self, forKeyPath: "contentOffset")` is called. Simply changing the `deinit` to `scrollView?.removeObserver(self, forKeyPath: "contentOffset")` fixes the issue.

**Comment by Krisiacik** [comment]
@yuriramocan You are very right! But instead of just properly calling a method on an optional, I will get rid of those optionals in the first place. I don't know what I was thinking when writing that code 😧

**Comment by Krisiacik** [comment]
This was fixed 
https://github.com/MailOnline/ImageViewer/releases/tag/2.0.6
