### ISSUE TITLE
Missing presentingViewController?.dismissViewControllerAnimated statement in ImageViewer.swift ?

### ISSUE THREAD

**Issue by betoHub** [MailOnline/ImageViewer#32]
I think a presentingViewController?.dismissViewControllerAnimated statement is missing at line 457 of ImageViewer.swift

Could be?

Anyway, great work!

**Comment by Krisiacik** [comment]
Why do you think so? We are canceling the swipe there. We do not want to dismiss because the swipe speed (finger movement speed) was too slow to swipe the image away. So that switch case reflects just that.

Thanks for using the library :)

**Comment by betoHub** [comment]
I noticed that if you swipe down very fast the image get stucked down and another tap is required to get the image repositioned, by adding that line instead, swiping down so fast it's the same of swiping up to dismiss the imageView!

**Comment by Krisiacik** [comment]
Are you looking at version 2.0.6?
![dismiss](https://cloud.githubusercontent.com/assets/9870899/15962245/8fec7532-2f01-11e6-8c0e-15d2a30d3103.png)

**Comment by Krisiacik** [comment]
This was a bug in an older release.
