### ISSUE TITLE
Ability to see faded/blurred view under image viewer

### ISSUE THREAD

**Issue by ealeksandrov** [MailOnline/ImageViewer#33]
How about adding property to tune black background alpha or even add blur to underneath view?
Like in [JTSImageViewController](https://github.com/jaredsinclair/JTSImageViewController):
![](https://raw.githubusercontent.com/jaredsinclair/JTSImageViewController/master/jts-image-viewer-screenshot.png)

Thanks for awesome library!

**Comment by Krisiacik** [comment]
That's a good idea. I have already implemented custom configurable colour for the background but I wasn't  happy with the result, white colour kind of worked well visually, but not other colours. Perhaps  the blur effect would give it an edge.

**Comment by Krisiacik** [comment]
This is now part of ImageViewer 3.0
