### ISSUE TITLE
Migrate to swift 3 and Xcode8

### ISSUE THREAD

**Issue by neoneye** [MailOnline/ImageViewer#34]
ImageViewer is awesome. I use ImageViewer in an app that is not going to be released any time soon. ImageViewer was easy to integrate with. Love your project.

Xcode8.0 beta was released yesterday and I have started [migrating my own projects to swift3](https://github.com/neoneye/SwiftyFORM/tree/feature/xcode80-beta).

Any plans for this?

**Comment by RuiAAPeres** [comment]
@neoneye we are currently at SF, next week we will look into it. (most probably we will create a swift3 branch a have the work there)

**Comment by RuiAAPeres** [comment]
@neoneye we might do this, a bit further down the line, as right now we don't have a lot of pressure to move to Xcode8. If you are interested, you can open a PR.
