### ISSUE TITLE
Cannot use with pod

### ISSUE THREAD

**Issue by NuVeS** [MailOnline/ImageViewer#36]
I add pod "ImageViewer" to pod file, make pod install and it installs. After that how to use ImageViewer class if there is no module to import and it does not see ImageViewer class?

**Comment by lfarah** [comment]
Hey @NuVeS, sometimes that happens. Just import wherever you import UIKit. I'm taking this from [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template)
To get the full benefits import `ImageViewer` wherever you import UIKit

``` swift
import UIKit
import ImageViewer
```
Sometimes Xcode won't recognize, so just press <kbd>shift</kbd> + <kbd>option</kbd>+<kbd>command</kbd> + <kbd>K</kbd> to clean the build.

If you prefer, you can also download and drop ```/ImageViewer``` folder in your project
