### ISSUE TITLE
Is it possible to add extra view at the bottom of gallery view?

### ISSUE THREAD

**Issue by sreeji44** [MailOnline/ImageViewer#39]
I need an extra view to add Comments, share, delete button at the bottom of gallery view.. is it possible to add

**Comment by Krisiacik** [comment]
Yes, prepare your view (or views in view hierarchy ) in advance and assign it to the footer view property.

**Comment by zfoltin** [comment]
Here it is in the example
https://github.com/MailOnline/ImageViewer/blob/master/Example/ViewController.swift#L41
