### ISSUE TITLE
Swift 3 and SwiftPM support

### ISSUE THREAD

**Issue by TofPlay** [MailOnline/ImageViewer#43]
Hi,
It's will be great to create a [Swift 3](https://swift.org/blog/swift-3-0-release-process/) version of your component 

Article about **Swift 3**: 
- [Migrating to Swift 2.3 or Swift 3 from Swift 2.2](https://swift.org/migration-guide/)

With [Swift 3](https://swift.org/blog/swift-3-0-release-process/) it would also be nice to add support for [SwiftPM](https://swift.org/package-manager/)

Articles about **SwiftPM**:
- [Package.swift — The Manifest File](https://github.com/apple/swift-package-manager/blob/master/Documentation/Package.swift.md)
- [Developing Packages](https://github.com/apple/swift-package-manager/blob/master/Documentation/DevelopingPackages.md)
- [System Modules](https://github.com/apple/swift-package-manager/blob/master/Documentation/SystemModules.md)
- [Swift Package Manager Community Proposal](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageManagerCommunityProposal.md)
 
On your `README.md` add [![SwiftPM Compatible](https://img.shields.io/badge/SwiftPM-Compatible-brightgreen.svg)](https://swift.org/package-manager/)  on top and add section for the installation with SwiftPM.

**Comment by RuiAAPeres** [comment]
@TofPlay would you be willing to create a PR with that work? We are currently busy and we are going to wait a bit longer until that migration.

**Comment by TofPlay** [comment]
@RuiAAPeres I'm also busy to prepare the migration to Swift 3 for my projects 😥

**Comment by andreyrd** [comment]
I got it to compile under Swift 3, but I haven't done any testing of it yet (won't be able to for a few more days), and I probably won't be able to check if the API ended up changing somewhere, because I haven't used this library prior to Swift 3.

Here it is: https://github.com/andreyrd/ImageViewer/tree/swift3

**Comment by FranciscoAmado** [comment]
@andreyrd try running the example project for your Swift 3 branch. I believe it isn't working properly. In mine, the whole functionality is unusable.

**Comment by zfoltin** [comment]
Swift 3 support is here \o/ https://github.com/MailOnline/ImageViewer/releases/tag/4.0

**Comment by ch-muhammad-adil** [comment]
My project is based on swift 3 and i have tried to use this library, it has given me these errors please take a look on screenshot. 

<img width="1280" alt="Screenshot 2019-04-16 at 1 48 11 AM" src="https://user-images.githubusercontent.com/8264639/56184617-23ff2380-6034-11e9-934f-4133dc6d8e03.png">
