### ISSUE TITLE
Is there any way to disable scroll horizontal to dismiss preview mode ?

### ISSUE THREAD

**Issue by biizc1150** [MailOnline/ImageViewer#47]
Is there any way to disable scroll horizontal to dismiss preview mode ?

Thanks :)

**Comment by Krisiacik** [comment]
Hi, 
not at the moment,  but it's a good idea. It would be very easy to allow this to be configured from the configuration.
I will add this to the list of 3.0 features.

Thanks :)

**Comment by RuiAAPeres** [comment]
@Krisiacik was this solved?

**Comment by zfoltin** [comment]
I don't think it has been implemented yet. PRs are welcome @biizc1150 :)

**Comment by Krisiacik** [comment]
This is now implemented. For now, it's part of master branch.
