### ISSUE TITLE
Configurable ImageView

### ISSUE THREAD

**Issue by ivanbruel** [MailOnline/ImageViewer#56]
I've been using [Kingfisher](https://github.com/onevcat/Kingfisher) as my image loading dependency alongside its `AnimatedImageView` which adds support for GIF loading.

As such, in order to take advantage of this in `ImageViewer` I had to make the `imageView` property public in the `ImageViewerController` class.

As this might be a problem for other people using different dependencies, might be nice to get this change into the library.

I've [forked](https://github.com/ivanbruel/ImageViewer) the project and made the change myself, let me know if it makes sense to open a pull request.

Example usage: 

``` swift
let buttonAssets = CloseButtonAssets(normal: closeIcon,
                                         highlighted: closeIcon)
let configuration = ImageViewerConfiguration(imageSize: CGSize(width: 10, height: 10),
                                                 closeButtonAssets: buttonAssets)
let imageViewer = ImageViewerController(imageProvider: viewModel, configuration: configuration,
                                            displacedView: view.imageView)
let imageView = AnimatedImageView()
imageView.framePreloadCount = 1
imageViewer.imageView = imageView
presentImageViewer(imageViewer)
```

**Comment by twalenciak** [comment]
+1 I've got similar issue with animated `ImageView` subclass, using [FLAnimatedImage](https://github.com/Flipboard/FLAnimatedImage), and also resolved this by fork and made this property public. 

I think possibility of providing custom `imageView` could be very convenient for many users.

**Comment by zfoltin** [comment]
Hey @ivanbruel & @twalenciak

ImageViewer changed a lot in v3.0. Now there is only the `GalleryViewController` where you provide `GalleryItem`s through a DataSource. A `GalleryItem` is either an image or a video at the moment.

I'm thinking if you create an extension on `AnimatedImageView` and `FLAnimatedImage` to conform to our `ItemView` protocol and return these views from your data source delegate then it should just work. The only requirement is to define an `image: UIImage?` property on the types. Does that make sense?

Would this solve the issue? Have you updated to v3.1 or v4.0 yet?

**Comment by zfoltin** [comment]
Ok, looking at the issue a bit closer, I've implemented a way to add custom ViewControllers to the gallery - this view controller can then work with a custom view
See the commit https://github.com/zfoltin/ImageViewer/commit/9eb10c16f3953eefdc6576147a2ca60c44bbd0a5
Particularly the bottom of Example/ViewController.swift shows how to integrate something like AnimatedImageView or FLAnimatedImageView

Any feedback welcome! :)

**Comment by zfoltin** [comment]
Hopefully https://github.com/MailOnline/ImageViewer/pull/80 helps if you need a custom GalleryItem. Closing for now but hoping to get some feedback @ivanbruel and @twalenciak if you find the time :)
