### ISSUE TITLE
Update cocoapods build with latest from repo

### ISSUE THREAD

**Issue by osolano** [MailOnline/ImageViewer#57]
It seems as if the version that is coming from cocoapods is an old version of ImageViewer.

With xcode 8, i'm forced to Swift 2.3 and the new version of ImageViewer can handle this.

My workaround is using this in my PodFile

`pod 'ImageViewer', :git => 'https://github.com/MailOnline/ImageViewer.git'`

but then this has an issue with missing file ThumbnailsViewController.swift and ThumbnailCell.swift

**Comment by pikor** [comment]
I have exactly the same issue! Would be great to see fix!

**Comment by zfoltin** [comment]
Hey @RuiAAPeres can you push the updated podspec from master to Cocoapods please?

**Comment by RuiAAPeres** [comment]
Done.
