### ISSUE TITLE
How to add videos in .carusel?

### ISSUE THREAD

**Issue by Luccifer** [MailOnline/ImageViewer#65]
Hello!

Faced a feature today, but no idea how to make it real.. In standard Apple "Photos".app we can swipe like carusel(thnx for this!) and sometimes can swipe it till video-files... How did they managed to do this and how to implement it in this library? Also will be a great enhancement to library as well in general...

**Comment by Krisiacik** [comment]
Version 3.0 supports both carousel and video playback. 
You can turn on Carousel behaviour in a configuration file and return video items in the delegate callbacks.

**Comment by Luccifer** [comment]
Yes, but images and videos i can swipe in the same carusel? Cause now it doesn't seems I can

**Comment by Krisiacik** [comment]
Yes off course you can :) ..it would be pointless to only have either videos OR images.
Its a matter of correct response in delegate callbacks that provide the image & video content.
Look at the example project inside the repo. It uses both videos and images together in one carousel.

**Comment by Luccifer** [comment]
Tanks a lot! You are awesome!

**Comment by zfoltin** [comment]
Aren't we all are? 😄
