### ISSUE TITLE
Wrong version in .podspec file for v3.0

### ISSUE THREAD

**Issue by vvit** [MailOnline/ImageViewer#66]
It seems it's not possible to install the version 3 via cocoapods?
The [.podspec](https://github.com/MailOnline/ImageViewer/blob/3.0/ImageViewer.podspec) of v3 points to v2.0.

I also used this line:
`pod 'ImageViewer', :git => 'git@github.com:MailOnline/ImageViewer.git', :tag => '3.0'` or 
`pod 'ImageViewer', :git => 'git@github.com:MailOnline/ImageViewer.git', :commit => 'f887383cc4fc32374f4096329253b2df5a79c11a'`

but it produces strange error:
`GalleryViewController.swift:367:36: Use of unresolved identifier 'ThumbnailsViewController'`.
Any ideas?

**Comment by zfoltin** [comment]
@RuiAAPeres can you 🔨 this?

**Comment by ealeksandrov** [comment]
```
GalleryViewController.swift:367:36: Use of unresolved identifier 'ThumbnailsViewController'
```

That's because in podspec `s.source_files  = "ImageViewer/Source/**/*"` and `GalleryViewController.swift` was stored above this path - in `"ImageViewer/"`. This was fixed during swift 3 migration - c456b4111c6ad0a2047178f62fe41bf5dff3aacf. Ad I'm not sure is it even possible to fix swift 2.3 version without rewriting the history.

I think I'll just create a fork with temp fix while I'm on Swift 2.3 and move to latest ImageViewer version after project migration to Swift 3.

**Comment by zfoltin** [comment]
@ealeksandrov we can branch out for 2.3 with the fix. Please create a PR once you have it and I'm sure @RuiAAPeres will look into pushing it to CocoaPods

**Comment by ealeksandrov** [comment]
Got it working. Can't create PR for the branch that don't exist here yet, so just linking: https://github.com/ealeksandrov/ImageViewer/tree/swift-2.3

Anyone can use it immediately by adding this line in `Podfile`:
```ruby
pod 'ImageViewer', :git => 'git@github.com:ealeksandrov/ImageViewer.git', :tag => '3.1'
```

**Comment by zfoltin** [comment]
https://github.com/MailOnline/ImageViewer/tree/swift-2.3

**Comment by ealeksandrov** [comment]
Thanks, here you are - #67

**Comment by Krisiacik** [comment]
I don't have access to cocoa pods.

**Comment by zfoltin** [comment]
Yeah, it's only @RuiAAPeres who has the power 💪 💥

**Comment by ealeksandrov** [comment]
Thanks for merging all stuff. Now we can get it working with:

```ruby
pod 'ImageViewer', :git => 'git@github.com:MailOnline/ImageViewer.git', :tag => '3.1'
```

Tested on my project, working fine. Last step will be `pod trunk push`.
