### ISSUE TITLE
Log for VideoScrubber

### ISSUE THREAD

**Issue by ealeksandrov** [MailOnline/ImageViewer#70]
I always see
```
VideoScrubber deinit 💣
```
on ImageViewer dismissing. Even when there are no videos in gallery. This is too verbose/unneeded log for me and most of users.

**Comment by Krisiacik** [comment]
PR is welcome.

**Comment by ChrisGriffiths** [comment]
#74

**Comment by ealeksandrov** [comment]
Thanks! :)
