### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by ealeksandrov** [MailOnline/ImageViewer#71]
I see verbose log of version changes and no instructions for quick start.

I propose moving changelog to `CHANGELOG.md` and adding quick start section with minimal instructions and delegate example for mix of local and remote images.

**Comment by Krisiacik** [comment]
With exception of verbose intro, which we are going to keep, PR with much improved instructions is very welcome.

**Comment by zfoltin** [comment]
We should also update the demo in https://github.com/MailOnline/ImageViewer/blob/master/Documentation/gallery.gif and show it in the readme. Let's see if I find the time before Christmas 🎅 🎄

**Comment by ealeksandrov** [comment]
@Krisiacik I am ok with verbose feature description, but it should be more compact and concise, without mentioning differences between versions - that's work for `changelog` :)

First iteration of improvements PR'd. Now don't forget to add `changelog` entries for any new features or bugfixes. I have an idea of adding [Danger](https://github.com/danger/danger) support to verify PRs, maybe in a future.

Don't hate me for creating a bunch of issues, I'll do my best to PR back and improve it when I have time 😄
I just liked architecture of this library and want it to be perfect! 🎉

**Comment by ealeksandrov** [comment]
Especially I liked how it supports whatever cache and networking stack you want for async image loading. I think it deserves highlight and couple of examples in `Readme`.

**Comment by zfoltin** [comment]
Thanks for the `CHANGELOG` PR @ealeksandrov 👌 every little helps 👍 
Danger would probably be an overkill at this point but will remember it when the need arise

Good point that we need to highlight the flexibility, configurability and extensibility of the library. Those are areas where it is particularly strong. Will try and improve the `README` on this front before 4.1 (4.1.0 😃) goes out.
