### ISSUE TITLE
How to force reloading of an image to get the (just downloaded) larger version?

### ISSUE THREAD

**Issue by antwerpenR** [MailOnline/ImageViewer#72]
Absolutely love ImageViewer!

I have put a gesture recogniser on the footerView to "Fetch a High Res Copy and Save to Camera Roll"....works fine..

..how can I force the page/gallery to reload the image so that it will pick up the larger version of the image for display?

**Comment by Krisiacik** [comment]
Thanks for the love :)
Reloading images is not possible at the moment I am afraid. Hm..hm..we would have to implement this.

**Comment by antwerpenR** [comment]
Hi!  Pity...if you can give any hints as to where/how might be the right place to do it - I might give it a do in my fork.  I am learning SOOOO much by reading your code!

**Comment by antwerpenR** [comment]
Thanks - works fine for me!

**Comment by nCr78** [comment]
Hello! Has this function changed in any way? I'm updating my data source and calling reload at the right index but nothing is happening.. I have to reinitialise the controller for it to show changes.

**Comment by JeromeTW** [comment]
@nCr78 , I have the same problem, did you fix it out? Thanks
