### ISSUE TITLE
Reverse presentation animation?

### ISSUE THREAD

**Issue by bennichols** [MailOnline/ImageViewer#73]
Hi, I'm wondering if there is a way to reverse the initial animation that opens up the viewer. I have an image that grows nicely onto the screen, and I'd like the dismiss animation to reverse that and shrink the image down to its original location. Is this possible?

**Comment by Krisiacik** [comment]
It is exactly what happens when you press the close button.

**Comment by bennichols** [comment]
I'm not seeing that behavior. When I hit the close button, the blur fades out and the old screen just pops into view. Maybe I'm not using it correctly? I'm basing off the example using the default configuration for the GalleryViewController.

**Comment by IvoPintodaSilva** [comment]
I'm facing the same problem using the following configuration:

```
let configuration: GalleryConfiguration = [
            /// presentation style
            GalleryConfigurationItem.presentationStyle(.displacement),
            GalleryConfigurationItem.statusBarHidden(true),
            
            /// top buttons
            GalleryConfigurationItem.thumbnailsButtonMode(.none),
            GalleryConfigurationItem.closeLayout(.pinRight(30, 30)),
            GalleryConfigurationItem.closeButtonMode(.custom(closeButton)),
            
            /// displacement technique
            //GalleryConfigurationItem.displacementKeepOriginalInPlace(false),
            GalleryConfigurationItem.displacementInsetMargin(20),
            GalleryConfigurationItem.displacementDuration(0.5),
            GalleryConfigurationItem.displacementTimingCurve(.easeInOut),
            GalleryConfigurationItem.reverseDisplacementDuration(0.5),
            
            /// disable fade and blur
            GalleryConfigurationItem.overlayBlurOpacity(0),
            GalleryConfigurationItem.itemFadeDuration(0),
            
        ]
```

When I press the close button, I want my image to be displaced into its original position of the parent view. However, this is not happening. The image viewer simply closes and shows the parent view abruptly without any kind of animation.

I have disabled fade and blur on purpose to show only the image displacement when closing the viewer.

Am I missing something here?

**Comment by IvoPintodaSilva** [comment]
Figured it out.

You need to implement the GalleryDisplacedViewsDatasource protocol in order to get the view into which the displacing is supposed finish.

You can see it in an example I created in my fork of the repo: https://github.com/IvoPintodaSilva/ImageViewer/tree/master/MyExample

Great library, however, this could be better documented :)

Keep up with the good work!

**Comment by Krisiacik** [comment]
I don't know what these Open Source authors think. They hastily write code and then fail to properly document it.

Oh wait. It was me. :) 
Well, happy to see you having resolved the problem. I'l keep in mind improvements in documentation have high priority.
