### ISSUE TITLE
Fullscreen gallery on not fullscreen modal view controller

### ISSUE THREAD

**Issue by IvoPintodaSilva** [MailOnline/ImageViewer#83]
Hey guys!

I've been using your lib a lot and I ran into a small issue (for my purposes).
I want to display the gallery from a not-fullscreen modal view controller. However, when I tried to do this, the blur view only covered that same view controller and left the rest of the screen visible.

I found out that it was happening because the blur view is being added to the parent view controller, so it keeps the size of the parent. 

To fix this I added the blur view to the back of the gallery instead, this way occupying the whole screen.

Is this the "correct" behaviour for the gallery and should I open a Pull Request or the current behaviour is best?

Cheers! 🍻

**Comment by zfoltin** [comment]
Hey @IvoPintodaSilva, your suggestion sounds sensible to me, PRs are more than welcome! 👍

**Comment by IvoPintodaSilva** [comment]
Opened PR #85 :)

**Comment by zfoltin** [comment]
Fixed by https://github.com/MailOnline/ImageViewer/pull/85
Thanks @IvoPintodaSilva 👍
