### ISSUE TITLE
Builtin close button assets missing

### ISSUE THREAD

**Issue by ealeksandrov** [MailOnline/ImageViewer#84]
```
button.setImage(UIImage(named: "close_normal"), forState: UIControlState.Normal)
button.setImage(UIImage(named: "close_highlighted"), forState: UIControlState.Highlighted)
```
Podspec doesn't add any assets. When I manually copied them from demo project it worked.

Idea - maybe draw it programmatically instead of using images?

**Comment by zfoltin** [comment]
Yeah, that bit is something we are not quite happy with. It's not nice to force people to add assets with a strictly given name either. Drawing a default close/closeHighlighted image programmatically would be a great improvement. We should also make `GalleryViewController.closeButton` open so people can override and use their own close button if they wanted.

Wanna do it @ealeksandrov ? :)

**Comment by Krisiacik** [comment]
Let's make buttons great again. 
My plan was always to eventually end up with custom vector-based close button consisting of UIVisualEffectView masked by a cross CAlayer/UIView.
Anybody up for it?

**Comment by ealeksandrov** [comment]
I'm in. Are you proposing UIVisualEffectView to add vibrancy effect?

**Comment by Krisiacik** [comment]
@ealeksandrov yes :)

**Comment by Krisiacik** [comment]
Although I have not validated it via some prototype..It might not work well visually. So do it only if you don't mind the effort.

**Comment by dasmer** [comment]
Looking forward to seeing this. The close button image does not show up using carthage either

**Comment by ealeksandrov** [comment]
PR: #90
No vibrancy for now, don't see a clean way to connect button with blurred background in current structure. It can be added in future iterations.
