### ISSUE TITLE
Async Image loading

### ISSUE THREAD

**Issue by Luccifer** [MailOnline/ImageViewer#93]
Hello! 
I am trying to show a very big (panorama) image in carusel and every time I swiping to this image it loads too long... The main thread is blocking by it, wondering about using this pod with ASDK from Facebook, but may be any other solutions? 

If I want to modyfy the UIImageView of this where should I "dig"?

Tnx anyway

Solved by using ASImageNode from ASDK(google it) replacing UIImageView

**Comment by baronha** [comment]
How to replace?  Please guide this newbie, I wanna use SDWebImage.
