### ISSUE TITLE
Close button 

### ISSUE THREAD

**Issue by junaid04** [MailOnline/ImageViewer#94]
Close button is not showing

**Comment by MDittmann** [comment]
For me the close button is not showing up too. Any idea what I'm doing wrong ? I use ImageViewer as a pod.

**Comment by zfoltin** [comment]
Sorry @MDittmann the pod version is a bit old.
The close button should be there in the pod version but the image on the button is tied to hardcoded image names (`close_highlighted` and `close_normal`). See https://github.com/MailOnline/ImageViewer/blob/4.0/ImageViewer/Source/Extensions/UIButton.swift#L98

Waiting for @RuiAAPeres to release a new version to Cocoapods as only he has access to it atm.

Alternatively you can specify the repo as the source of the pod, something like:
`pod 'ImageViewer', :git => 'https://github.com/MailOnline/ImageViewer.git'`
