### ISSUE TITLE
Zooming bug on some devices/images

### ISSUE THREAD

**Issue by jesalgadom** [MailOnline/ImageViewer#96]
In some cases with some devices (i.e: iPhone 7plus simulator and image 7/7 of the example), the return from `AVMakeRectWithAspectRatioInsideRect` in `aspectFitContentSize:` has some decimals that makes this comparison to be false, provoking a bug when zooming in.

Using `floor()` for this comparison makes the trick. I already created the fix on my fork. Let me know if you agree and want me to create a PR to master.

**Comment by Krisiacik** [comment]
Sure...please bring it on! :)
